version = 1

[[matches]]
stage = 0
completed = false
opponent = 'Johnathon "Turtling" Douglas'
ais = ['Fast Tanyao', 'AngryDiscardoBot', 'AngryDiscardoBot']
intro=[
    'Test',
    'This is a second dialogue line',
    "Let's get started"
]
call_pon='haha!'
call_chi='hoho!'
call_kan='hehe!'
call_ron='nothing personal kid.'
on_player_wins="wow! you're not half bad kid."
on_player_loses="hehe, better luck next time."
on_both_lose="well, I guess we both have some improving to do."