
name: Build and Release Pipelines

on:
  push:
    branches: [ mainline ]
  pull_request:
    branches: [ mainline ]

jobs:

  windows-build:
    name: Windows Build
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: Set usage of Python 3.8
      run: setx PY_PYTHON 3.8

    - name: Install Python Dependencies
      run: py -m pip install -r requirements.txt --user

    - name: Install Twine
      run: py -m pip install -U twine --user

    - name: Create CMake Environment
      run: cmake -G"Visual Studio 16 2019" -S . -B build -DPACKAGE_TESTS=OFF

    - name: Build Library
      run: cmake --build build

    - name: Display Build Folder
      run: dir .\libmahjong\

    - name: Upload built artifact
      uses: actions/upload-artifact@v2
      with:
        name: windowsbuild
        path: libmahjong/libmahjong.so

  linux-build:
    name: Linux Build
    needs: windows-build
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true

    - name: Install Depedencies
      run: sudo apt-get install python3

    - name: Create CMake Environment
      run: CC=clang CXX=clang++ CXXFLAGS="-isystem /usr/lib/llvm-9/lib/clang/9.0.0/include" cmake -S . -B build -DPACKAGE_TESTS=OFF

    - name: Install Python Packages
      run: pip install -r requirements.txt --user

    - name: Download Windows Build
      uses: actions/download-artifact@v2
      with:
        name: windowsbuild
        path: libmahjong/

    - name: Rename Windows Pyd
      run: mv libmahjong/libmahjong.so libmahjong/libmahjong.pyd

    - name: Display Build Folder 1
      run: ls libmahjong

    - name: Build Library
      run: cmake --build build

    - name: Display Build Folder 2
      run: ls libmahjong

    - name: Package Project
      run: python3 setup.py sdist

    - name: Show Built Distributions
      run: ls dist/

    - name: Publish Build to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}